// src/lib/components/header/Header.svelte
<header class="flex justify-between items-center container mx-auto py-4 max-h-[72px]">
	<div>
		<h1 class="text-4xl text-primary">MB</h1>
	</div>
	<nav class="text-2xl font-thin">
		<ul class="flex gap-10">
			<li class="uppercase">
				<a href="#section-2">Projects</a>
			</li>
			<li class="uppercase">
				<a href="#section-3">Contact</a>
			</li>
		</ul>
	</nav>
</header>

// src/components/header.tsx
import { ThemeSwitcher } from './themeSwitcher';
import { GeistMono } from 'geist/font/mono';

export default function Header() {
  return (
    <header className={`${GeistMono.className} relative tracking-tight md:mb-8`}>
      <nav className="max-w-[576px] mx-auto flex justify-between pt-8 items-center px-6">
        <Link className="font-bold text-2xl hidden md:block" href={'/'}>
          <h1>MARTIN BRUUN</h1>
        </Link>
        <Link className="font-bold text-2xl md:hidden" href={'/'}>
          <h1>MB</h1>
        </Link>
        <ul className="flex gap-2 items-center">
          <li>
            <ThemeSwitcher />
          </li>
        </ul>
      </nav>
    </header>
  );
}
